import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

void i18n.use(initReactI18next).init({
  lng: 'en', fallbackLng: 'en', interpolation: { escapeValue: false },
  resources: { en: { translation: {
    brand: 'Document Platform', workspace: 'Your workspace', eyebrow: 'A place for every document',
    heading: 'Good documents start here.', description: 'Explore your first template and make yourself at home.',
    templates: 'Templates', sample: 'Sample template', open: 'Explore template', starterEyebrow: 'Start from a template', starterGallery: 'Multilingual starters', starterGalleryNote: 'Choose a starter family and language to create a draft in the workspace.', useStarter: 'Use starter',
    loading: 'Loading your workspace...', error: 'We could not load your workspace. Please try again.',
    retry: 'Try again', empty: 'No templates yet.', status: 'Workspace status', ready: 'Connected',
    unavailable: 'Needs attention', database: 'Database', storage: 'Document storage', frontend: 'Application',
    starting: 'Checking connection', back: 'Back to templates', structure: 'Document structure',
    data: 'Sample data', future: 'Editing and document generation are coming in the next milestones.',
    letter: 'Welcome letter', letterDescription: 'A simple welcome letter with a recipient field and sample data.',
    footer: 'Your documents. Your infrastructure.', api: 'API reference', unknownStatus: 'Connection check unavailable',
    projectEyebrow: 'Delivery snapshot', projectStatus: 'Project status', statusSnapshot: 'Current foundation view', viewProjectStatus: 'View project status', backToWorkspace: 'Back to workspace', overallStatus: 'Overall status', overallProgress: 'Overall project progress', projectNote: 'Weights follow the number of source stories in each epic and total 100.0. Progress counts only evidence-backed implementation, not planned scope.', epicTableCaption: 'Epic stories and delivery status', storyId: 'Story ID', story: 'Story', priority: 'Priority', size: 'Size', storyStatus: 'Status', 'storyStatus.implemented': 'Implemented', 'storyStatus.partial': 'Partial', 'storyStatus.planned': 'Planned', weight: 'Weight', of: 'of', 'in-progress': 'In progress', planned: 'Planned',
    editorDraftNote: 'Local draft preview only. Saving and final document output will follow the template and rendering milestones.', editorToolbar: 'Text formatting controls', bold: 'Bold', italic: 'Italic', textColor: 'Text colour', alignment: 'Alignment', left: 'Left', center: 'Center', right: 'Right', addTextBlock: 'Add text block', textBlocks: 'Text blocks', selectBlock: 'Select text block', editBlock: 'Edit text block', preview: 'Preview', localPreview: 'Local preview', ingestionEyebrow: 'Digitization intake', ingestionTitle: 'Upload source documents', ingestionNote: 'Upload PDF or image files. Each file is routed independently; OCR and layout extraction run in later processing milestones.', chooseFiles: 'Choose files', uploading: 'Uploading…', queued: 'Queued', failed: 'Failed', uploadFailed: 'Upload failed',
    pages: 'pages', extractionSchema: 'Extraction schema', editSchema: 'Edit schema JSON', schemaJson: 'Extraction schema JSON', validateSchema: 'Validate schema', schemaValid: 'Schema is valid', schemaInvalid: 'Schema is invalid', schemaJsonInvalid: 'Schema JSON is invalid', extract: 'Extract selected schema', extracting: 'Extracting…', extractionFailed: 'Extraction failed', reviewReady: 'Review ready', reviewEyebrow: 'Correction workflow', reviewTitle: 'Review extracted fields', reviewNote: 'Select a field or source region to highlight its stored provenance box. Image uploads show the source beside the overlay; PDF review uses PageModel coordinates until rasterization is available.', reviewQueue: 'Keyboard review queue', reviewQueueHint: 'Failed rules first, then low confidence. Enter or arrow keys move between fields.', failedRule: 'failed rule', lowConfidence: 'low confidence', reviewed: 'review', confidence: 'Confidence', approve: 'Approve', reject: 'Reject', sendToTemplate: 'Send to template', saveFailed: 'Save failed', renderFailed: 'Template render failed',
    font: 'Font', fontSize: 'Size', pageBreakBefore: 'Start on new page', keepTogether: 'Keep block together', pageSettings: 'Page settings', previewLocale: 'Preview locale', documentTitle: 'Document title', documentAuthor: 'Document author', pageSize: 'Page size', orientation: 'Orientation', portrait: 'Portrait', landscape: 'Landscape', margins: 'Margins', pageHeader: 'Header', pageFooter: 'Footer', pageNumbers: 'Show page numbers', addTableBlock: 'Add repeatable table', addRepeatBlock: 'Add repeating section', addConditionalBlock: 'Add conditional block', tableBlock: 'Repeatable table', logicBlocks: 'Repeatable and conditional blocks', tableItems: 'Data array path', tableColumns: 'Columns JSON', repeatItems: 'Repeat data array', repeatText: 'Repeated text', conditionPath: 'Condition field', conditionEnabled: 'Condition enabled', thenText: 'If true', elseText: 'If false', saveDraft: 'Save draft', editorSaved: 'Draft saved and server preview rendered', editorSaveFailed: 'Draft could not be saved', editorRenderFailed: 'Draft saved, but server preview failed', serverPreview: 'Server preview', renderDiagnostics: 'Render diagnostics', renderEngine: 'Engine', renderStatus: 'Status', detectedScripts: 'Detected scripts', fontStacks: 'Requested font stacks', script: 'Script', requestedStack: 'Requested stack', embeddedFonts: 'Embedded fonts', missingGlyphs: 'Missing glyphs', diagnosticStatus: 'Diagnostic status', generatePdf: 'Generate PDF', generatingPdf: 'Generating PDF…', pdfGenerated: 'PDF generated', pdfGenerateFailed: 'PDF generation failed', pdfPreview: 'Generated PDF', downloadPdf: 'Download PDF',
  } } },
})
i18n.addResources('en', 'translation', { addImageBlock: 'Add image or logo', imageSource: 'Image source or URL', imageUpload: 'Upload image', imageAlt: 'Alt text', imageWidth: 'Width', addCodeBlock: 'Add QR or barcode', codeType: 'Code type', codeValue: 'Code value', markAbsent: 'Mark absent', newFieldName: 'New field name', addMissingField: 'Add field from selected source', undoCorrection: 'Undo latest correction', addFieldRequiresNameAndSource: 'Enter a field name and select a source region first', undoFailed: 'Undo failed', additionalScriptLocales: 'Additional script locales', hebrew: 'Hebrew', tamil: 'Tamil', korean: 'Korean' })

i18n.addResources('en', 'translation', { undo: 'Undo', redo: 'Redo', copy: 'Copy', paste: 'Paste', snap: 'Snap & guides', alignLeft: 'Align left', alignCenter: 'Align center', alignRight: 'Align right', reusableComponents: 'Reusable components', saveAsComponent: 'Save selection as component', updateComponent: 'Update component from selection', componentUpdated: 'Component updated', addComponent: 'Add component', removeComponent: 'Remove component', deleteBlock: 'Delete selected block' })

i18n.addResources('en', 'translation', { generateSampleData: 'Generate sample data', sampleDataGenerated: 'Sample data generated', addChartBlock: 'Add chart', addTocBlock: 'Add table of contents', themeAccent: 'Theme accent', themeControls: 'Theme controls', themeFont: 'Theme font', themeSpacing: 'Theme spacing', pageBackground: 'Page background', pdfBackground: 'Locked PDF page background', structureControls: 'Structure controls', anchorId: 'Anchor ID', tocLabel: 'TOC label', tocLabelPlaceholder: 'Section heading', tocLevel: 'TOC level', chartControls: 'Chart controls', chartType: 'Chart type', chartItems: 'Chart data path', chartLabelPath: 'Chart label path', chartValuePath: 'Chart value path' })

export default i18n
