import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

void i18n.use(initReactI18next).init({
  lng: 'en', fallbackLng: 'en', interpolation: { escapeValue: false },
  resources: { en: { translation: {
    brand: 'Document Platform', workspace: 'Your workspace', signIn: 'Sign in', signInTitle: 'Sign in to your workspace', setupTitle: 'Set up your administrator account', createAccount: 'Create account', authNote: 'Use your organization account, continue as a restricted guest, or sign up with your email.', email: 'Email address', password: 'Password', continueAsGuest: 'Continue as guest', signUp: 'Sign up', signUpEmail: 'New account email', ssoSignIn: 'Sign in with SSO', ssoNotConfigured: 'SSO is ready for provider configuration but is not enabled in this deployment.', signOut: 'Sign out',
    eyebrow: 'A place for every document',
    heading: 'Good documents start here.', description: 'Explore your first template and make yourself at home.',
    templates: 'Templates', sample: 'Sample template', open: 'Explore template', workspaceFolder: 'Workspace', starterEyebrow: 'Start from a template', starterGallery: 'Template gallery', starterGalleryNote: 'Browse templates by industry and start with a ready-made document.', useStarter: 'Use starter', moreTemplates: 'More templates', fewerTemplates: 'Show fewer', createBlankTemplate: 'Create blank template', blankTemplateHint: 'Start with an empty canvas. Name and organize it when you save.', blankTemplateName: 'Template name', blankTemplateFolder: 'Folder', blankTemplateNamePlaceholder: 'e.g. Quarterly client report', blankTemplateFolderPlaceholder: 'e.g. Wealth / Client reports', blankTemplateNameRequired: 'Enter a template name first.', blankTemplateFailed: 'The blank template could not be created.',
    loading: 'Loading your workspace...', error: 'We could not load your workspace. Please try again.', organizationTemplates: 'Organization templates', organizationTemplatesNote: 'Templates shared in your organization workspaces.', myTemplatesNote: 'Templates you own in your personal workspace.', myTemplatesEmpty: 'You have not created any templates yet.', loadMoreOrganization: 'Load more organization templates',
    retry: 'Try again', empty: 'No templates yet.', status: 'Workspace status', ready: 'Connected',
    unavailable: 'Needs attention', database: 'Database', storage: 'Document storage', frontend: 'Application',
    starting: 'Checking connection', back: 'Back to templates', structure: 'Document structure',
    data: 'Sample data', future: 'Editing and document generation are coming in the next milestones.',
    letter: 'Welcome letter', letterDescription: 'A simple welcome letter with a recipient field and sample data.',
    footer: 'Your documents. Your infrastructure.', api: 'API reference', unknownStatus: 'Connection check unavailable',
    projectEyebrow: 'Delivery snapshot', projectStatus: 'Project status', statusSnapshot: 'Current foundation view', viewProjectStatus: 'View project status', backToWorkspace: 'Back to workspace', overallStatus: 'Overall status', overallProgress: 'Overall project progress', projectNote: 'Weights follow the number of source stories in each epic and total 100.0. Progress counts only evidence-backed implementation, not planned scope.', epicTableCaption: 'Epic stories and delivery status', storyId: 'Story ID', story: 'Story', priority: 'Priority', size: 'Size', storyStatus: 'Status', 'storyStatus.implemented': 'Implemented', 'storyStatus.partial': 'Partial', 'storyStatus.planned': 'Planned', weight: 'Weight', of: 'of', 'in-progress': 'In progress', planned: 'Planned',
    editorDraftNote: 'Local draft preview only. Saving and final document output will follow the template and rendering milestones.', editorToolbar: 'Text formatting controls', bold: 'Bold', italic: 'Italic', textColor: 'Text colour', alignment: 'Alignment', left: 'Left', center: 'Center', right: 'Right', addTextBlock: 'Add text block', textBlocks: 'Text blocks', selectBlock: 'Select text block', editBlock: 'Edit text block', preview: 'Preview', localPreview: 'Local preview', ingestionEyebrow: 'Digitization intake', ingestionTitle: 'Upload source documents', ingestionNote: 'Upload PDF or image files. Each file is routed independently; OCR and layout extraction run in later processing milestones.', chooseFiles: 'Choose files', uploading: 'Uploading…', queued: 'Queued', failed: 'Failed', uploadFailed: 'Upload failed',
    pages: 'pages', extractionSchema: 'Extraction schema', editSchema: 'Edit schema JSON', schemaJson: 'Extraction schema JSON', validateSchema: 'Validate schema', schemaValid: 'Schema is valid', schemaInvalid: 'Schema is invalid', schemaJsonInvalid: 'Schema JSON is invalid', extract: 'Extract selected schema', extracting: 'Extracting…', extractionFailed: 'Extraction failed', reviewReady: 'Review ready', reviewEyebrow: 'Correction workflow', reviewTitle: 'Review extracted fields', reviewNote: 'Select a field or source region to highlight its stored provenance box. Image uploads show the source beside the overlay; PDF review uses PageModel coordinates until rasterization is available.', reviewQueue: 'Keyboard review queue', reviewQueueHint: 'Failed rules first, then low confidence. Enter or arrow keys move between fields.', failedRule: 'failed rule', lowConfidence: 'low confidence', reviewed: 'review', confidence: 'Confidence', approve: 'Approve', reject: 'Reject', sendToTemplate: 'Send to template', saveFailed: 'Save failed', renderFailed: 'Template render failed',
    font: 'Font', fontSize: 'Size', pageBreakBefore: 'Start on new page', keepTogether: 'Keep block together', pageSettings: 'Page settings', previewLocale: 'Preview locale', documentTitle: 'Document title', documentAuthor: 'Document author', pageSize: 'Page size', orientation: 'Orientation', portrait: 'Portrait', landscape: 'Landscape', margins: 'Margins', pageHeader: 'Header', pageFooter: 'Footer', pageNumbers: 'Show page numbers', headerAlign: 'Header alignment', footerAlign: 'Footer alignment', pageNumberPosition: 'Page number position', pageNumberFormat: 'Page number format', headerFooterFontSize: 'Header/footer size', addTableBlock: 'Add repeatable table', addRepeatBlock: 'Add repeating section', addConditionalBlock: 'Add conditional block', tableBlock: 'Repeatable table', logicBlocks: 'Repeatable and conditional blocks', tableItems: 'Data array path', tableColumns: 'Columns JSON', repeatItems: 'Repeat data array', repeatText: 'Repeated text', conditionPath: 'Condition field', conditionEnabled: 'Condition enabled', thenText: 'If true', elseText: 'If false', saveDraft: 'Save draft', editorSaved: 'Draft saved and server preview rendered', editorSaveFailed: 'Draft could not be saved', editorRenderFailed: 'Draft saved, but server preview failed', serverPreview: 'Server preview', renderDiagnostics: 'Render diagnostics', renderEngine: 'Engine', renderStatus: 'Status', detectedScripts: 'Detected scripts', fontStacks: 'Requested font stacks', script: 'Script', requestedStack: 'Requested stack', embeddedFonts: 'Embedded fonts', missingGlyphs: 'Missing glyphs', diagnosticStatus: 'Diagnostic status', generatePdf: 'Generate PDF', generatingPdf: 'Generating PDF…', pdfGenerated: 'PDF generated', pdfGenerateFailed: 'PDF generation failed', pdfPreview: 'Generated PDF', downloadPdf: 'Download PDF',
  } } },
})
i18n.addResources('en', 'translation', { draftReadyToSave: 'Draft ready to save. Choose Save template as to name and organize it.' })
i18n.addResources('en', 'translation', { addImageBlock: 'Add image or logo', imageSource: 'Image source or URL', imageUpload: 'Upload image', imageAlt: 'Alt text', imageWidth: 'Width', addCodeBlock: 'Add QR or barcode', codeType: 'Code type', codeValue: 'Code value', markAbsent: 'Mark absent', newFieldName: 'New field name', addMissingField: 'Add field from selected source', undoCorrection: 'Undo latest correction', addFieldRequiresNameAndSource: 'Enter a field name and select a source region first', undoFailed: 'Undo failed', additionalScriptLocales: 'Additional script locales', hebrew: 'Hebrew', tamil: 'Tamil', korean: 'Korean' })

i18n.addResources('en', 'translation', { undo: 'Undo', redo: 'Redo', copy: 'Copy', paste: 'Paste', snap: 'Snap & guides', alignLeft: 'Align left', alignCenter: 'Align center', alignRight: 'Align right', alignJustify: 'Justify', reusableComponents: 'Reusable components', saveAsComponent: 'Save selection as component', updateComponent: 'Save component changes', componentUpdated: 'Component updated', addComponent: 'Add component', removeComponent: 'Remove component', deleteBlock: 'Delete selected block', textFormatting: 'Text formatting' })
i18n.addResources('en', 'translation', { insertObjects: 'Insert objects', documentStructure: 'Document structure', layers: 'Layers', layerHint: 'Select an object to inspect its layer actions.', contextualActions: 'Contextual actions', selectedObject: 'Selected object', noObjectSelected: 'Select an object to see actions.', position: 'Position', properties: 'Properties', objectProperties: 'Object properties', visualObjectSelected: 'Visual object selected', contextualActionHint: 'Actions adapt to the selected object.', compositeComponentHint: 'Composite components expose their child actions when a child is selected.' })
i18n.addResources('en', 'translation', { editorCommandBar: 'Editor command bar', readyToEdit: 'Ready to edit' })
i18n.addResources('en', 'translation', { moveLeft: 'Move left', moveRight: 'Move right' })
i18n.addResources('en', 'translation', { componentChildren: 'Component children', componentChildrenUnavailable: 'No child objects are available for this component.', componentLibrary: 'Component library', componentLibraryHint: 'Save a selected group of blocks once, then reuse it in any template.', componentSearch: 'Search components', componentName: 'New component name', componentNamePlaceholder: 'e.g. Branded signature block', componentSelectionCount: '{{count}} selected', componentSelectBlocks: 'Select one or more blocks before saving a component.', componentNameRequired: 'Enter a component name first.', componentSaveFailed: 'The component could not be saved.', componentSaved: 'Component saved and inserted into this template.', componentNoMatches: 'No components match your search.', componentLibraryEmpty: 'No reusable components yet.', componentVersion: 'Version', insertComponent: 'Insert', componentReference: 'Component reference', componentUpdateHint: 'Select a component reference and its child blocks to update it.' })
i18n.addResources('en', 'translation', { imageControls: 'Image controls', enlargeImage: 'Make image bigger', shrinkImage: 'Make image smaller', moveUp: 'Move up', moveDown: 'Move down', saveTemplate: 'Save template as', templateNamePrompt: 'Template name', templateFolderPrompt: 'Folder name (optional)', templateSaved: 'Template saved', templateSaveFailed: 'Template could not be saved', templateSettings: 'Template settings', editorSettings: 'Editor settings', templateSchemaUpload: 'Upload JSON schema', templateSchemaValid: 'JSON schema is valid and bound to this template version', templateSchemaJsonInvalid: 'The uploaded file is not valid JSON', templateSchemaBound: 'Schema bound', templateSchemaNotBound: 'No schema bound to this template version', myTemplates: 'My templates', latestEdited: 'Latest 10 edited templates' })
i18n.addResources('en', 'translation', { topMargin: 'Top margin', rightMargin: 'Right margin', bottomMargin: 'Bottom margin', leftMargin: 'Left margin', headerComponent: 'Header component', footerComponent: 'Footer component', noComponent: 'No component' })

i18n.addResources('en', 'translation', { generateSampleData: 'Generate sample data', sampleDataGenerated: 'Sample data generated', addChartBlock: 'Add chart', addChart: 'Add chart', addShapeBlock: 'Add line or rectangle', addColumns: 'Start columns', addColumnBreak: 'Column break', addColumnsEnd: 'End columns', chart: 'chart', addTocBlock: 'Add table of contents', addPdfBackground: 'Add locked PDF background', replacePdfBackground: 'Replace locked PDF background', resetPdfBackground: 'Reset locked PDF background', resetPageBackground: 'Reset page background', pdfBackgroundSet: 'Locked PDF background is set', noPdfBackground: 'No locked PDF background', themeAccent: 'Theme accent', themeControls: 'Theme controls', themeFont: 'Theme font', themeSpacing: 'Theme spacing', pageBackground: 'Page background', pdfBackground: 'Locked PDF page background', structureControls: 'Structure controls', anchorId: 'Anchor ID', tocLabel: 'TOC label', tocLabelPlaceholder: 'Section heading', tocLevel: 'TOC level', chartControls: 'Chart controls', chartType: 'Chart type', chartItems: 'Chart data path', chartLabelPath: 'Chart label path', chartValuePath: 'Chart value path', chartTitle: 'Chart title', chartOrientation: 'Bar orientation', vertical: 'Vertical', horizontal: 'Horizontal', showPoints: 'Show points', showGrid: 'Show grid', donut: 'Donut style', showLegend: 'Show legend', xAxisLabel: 'X-axis label', yAxisLabel: 'Y-axis label' })

export default i18n
